# Wiki.js Navigation Configuration
# Place this file in the ato-ebook directory

title: ATO in Days, Not Years
navigation:
  - home
  - title: Chapters
    children:
      - chapter-1-the-compliance-rosetta-stone
      - chapter-2-machine-readable-compliance
      - chapter-3-evidence-automation-checklist
      - chapter-4-the-90-day-sprint
      - chapter-5-the-authorization-briefing
  - title: Templates & Resources
    children:
      - templates/home
      - templates/mapping-matrix
      - templates/oscal-ssp
      - templates/evidence-scripts
      - templates/sprint-planner
      - templates/briefing-deck
  - visual-design-brief
